# Use root/example as user/password credentials
version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    networks:
      - my_net

  db:
#    image: mysql:8.0.32-oracle
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: link_zipper_dj_db
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_user_password
      MYSQL_ROOT_PASSWORD: mysql_root_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_net

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    networks:
      - my_net
    ports:
      - '8080:8080'

  redis:
    image: redis:7.0.9
    networks:
      - my_net


networks:
  my_net:
    driver: bridge

volumes:
  mysql_data:
    driver: local
