# Use root/example as user/password credentials
version: "3.8"

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - my_net

  db:
    image: mysql:8.0.32-debian
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/logs:/var/log/mysql
#    command: mysqld --general-log=1 --general-log-file=/var/lib/mysql/general-log.log
    command: mysqld --general-log=1 --general-log-file=/var/log/mysql/general-log.log
    user: ${LOCAL_USER_ID:-1000}:${LOCAL_GROUP_ID:-1000}
    networks:
      - my_net

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    networks:
      - my_net
    ports:
      - "8080:8080"

  redis:
    image: redis:7.0.9
    networks:
      - my_net


networks:
  my_net:
    driver: bridge
