# Use root/example as user/password credentials
version: "3.8"

services:

  db:
    image: mysql:8.0.32-debian
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/logs:/var/log/mysql
    user: ${LOCAL_USER_ID:-1000}:${LOCAL_GROUP_ID:-1000}
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"

  redis:
    image: redis:7.0.9
    ports:
      - "6379:6379"
