# Generated by Django 4.1.7 on 2023-03-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="zipped_url",
            field=models.CharField(max_length=1024, verbose_name="Сжатая ссылка"),
        ),
    ]
